#!/bin/bash
. /etc/log2zram.conf

echo $$ > /usr/local/bin/log2zram/log2zram-schd-pid

PRUNE_LOG=/var/prune.log
ZRAM_LOG=/var/log

getUsage () {
	BYTES_AVAIL=$(df "/var/log" | tail -1 | awk '{ print $4 }')
	BYTES_USED=$(df "/var/log" | tail -1 | awk '{ print $3 }')
	
}

pruneOldLog() {
	getUsage
	LOG_REMAINING=$(( ${BYTES_AVAIL} * 100  / (${BYTES_AVAIL} + ${BYTES_USED}) ))
	if [ "$LOG_REMAINING" -lt "$PRUNE_LEVEL" ];then
			cp -arvf $ZRAM_LOG -T $PRUNE_LOG 2>&1 | logger &
			rm -rf $ZRAM_LOG/oldlog/* 
	fi
	
}

ROTATE_COUNTER=1
PRUNE_COUNTER=1
while :
do
	sleep 60
	ROTATE_COUNTER=$((ROTATE_COUNTER + 1))
	PRUNE_COUNTER=$((PRUNE_COUNTER + 1))
	
	if [ ! -z "$LOGROTATE_FREQ" ]
	then
		if [  "$LOGROTATE_FREQ" -lt "$ROTATE_COUNTER"  ]
		then
			echo "log2zram-sch forced logrotate"  2>&1 | logger &
			/usr/sbin/logrotate -vf /etc/logrotate.conf 2>&1 | logger &
			ROTATE_COUNTER=1
		fi
	fi

	
	if [  "$PRUNE_FREQ" -lt "$PRUNE_COUNTER"  ]
	then
		pruneOldLog
		PRUNE_COUNTER=1
	fi
done
