#!/bin/bash

. /etc/log2zram.conf

HDD_LOG=/var/hdd.log
ZRAM_LOG=/var/log

isSafe () {
	[ -d $HDD_LOG/ ] || echo "ERROR: $HDD_LOG/ doesn't exist! Can't sync." 
	[ -d $HDD_LOG/ ] || exit 1
}

syncToDisk () {
	isSafe
	rsync -arvzh $ZRAM_LOG/ $HDD_LOG/ 

}

syncFromDisk () {
	isSafe
	getUsage
	LOG_SIZE=$(du -sk $HDD_LOG/ | awk '{ print $1 }')
	if [ "$BYTES_AVAIL" -lt "$LOG_SIZE" ];then
		echo "ERROR: RAM disk too small. Can't sync." 
		umount -l $ZRAM_LOG/
		umount -l $HDD_LOG/
		exit 1
	fi
	rsync -arvzh --exclude='oldlog' $HDD_LOG/ $ZRAM_LOG/ 
	mkdir -p /var/log/oldlog
	chmod 754 /var/log/oldlog
	chown root:adm /var/log/oldlog
}

wait_for () {
	while ! grep -qs "$1" /proc/mounts; do
		sleep 0.1
	done
}

createZramLogDrive () {
	# Check Zram Class created
	if [ ! -d "/sys/class/zram-control" ]; then
		modprobe --verbose zram
		ZRAM_DEV='0'
	else
		ZRAM_DEV=$(cat /sys/class/zram-control/hot_add)
	fi
	echo ${COMP_ALG} > /sys/block/zram${ZRAM_DEV}/comp_algorithm
	echo ${LOG_DISK_SIZE} > /sys/block/zram${ZRAM_DEV}/disksize
	echo ${SIZE} > /sys/block/zram${ZRAM_DEV}/mem_limit
	mke2fs -v -t ext4 /dev/zram${ZRAM_DEV}
}

getUsage () {
	BYTES_AVAIL=$(df "/var/log" | tail -1 | awk '{ print $4 }')
	BYTES_USED=$(df "/var/log" | tail -1 | awk '{ print $3 }')
	
}


pruneOldLog() {
	isSafe
	getUsage
	LOG_REMAINING=$(( ${BYTES_AVAIL} * 100  / (${BYTES_AVAIL} + ${BYTES_USED}) ))
	if [ "$LOG_REMAINING" -lt "$PRUNE_LEVEL" ];then
			rsync -avrzh $ZRAM_LOG/oldlog/ $HDD_LOG/oldlog/ 
			rm -rf $ZRAM_LOG/oldlog/* 
	fi
	
}

case "$1" in
	start)
		mount --verbose --bind $ZRAM_LOG/ $HDD_LOG/
		mount --verbose --make-private $HDD_LOG/
		wait_for $HDD_LOG
		createZramLogDrive
		mount --verbose --types ext4 /dev/zram${ZRAM_DEV} ${ZRAM_LOG}/
		wait_for $ZRAM_LOG
		syncFromDisk
		if [  "$LOGROTATE_FREQ" -gt 0  ]
		then
			mv -f /etc/cron.daily/logrotate /usr/local/bin/log2zram/logrotate
		fi
		nohup /usr/local/bin/log2zram/log2zram-schd > /dev/null 2>&1 &
		;;

	stop)
		syncToDisk
		umount -l $ZRAM_LOG/
		umount -l $HDD_LOG/
		kill $(cat /usr/local/bin/log2zram/log2zram-schd-pid)
		if [  "$LOGROTATE_FREQ" -gt 0  ]
		then
			mv /usr/local/bin/log2zram/logrotate /etc/cron.daily/logrotate
		fi
		;;

	prune)
		pruneOldLog
		;;

	*)
		echo "Usage: log2ram {start|stop|write}" >&2
		exit 1
	;;
esac
