#!/bin/bash

. /etc/log2zram.conf


ZRAM_LOG=/var/log
ZSHARE=/usr/local/share/log2zram
ZLOG=${ZSHARE}/log/log2zram.log


createZramLogDrive () {
	# Check Zram Class created
	if modprobe --verbose --first-time zram  >>${ZLOG} 2>&1
	then
		DEV_NUM='0'
	else
		DEV_NUM=$(cat /sys/class/zram-control/hot_add)
	fi
	echo ${COMP_ALG} > /sys/block/zram${DEV_NUM}/comp_algorithm
	echo ${LOG_DISK_SIZE} > /sys/block/zram${DEV_NUM}/disksize
	echo ${SIZE} > /sys/block/zram${DEV_NUM}/mem_limit
	mke2fs -v -t ext4 $MKFS_OPTS /dev/zram${DEV_NUM} >>${ZLOG} 2>&1 || return 1
}

mergeOverlay () {
	echo "overlay lowerdir=${HDD_LOG},upperdir=${ZDIR}/zram${DEV_NUM}/upper" >>${ZLOG}
	cd /usr/local/lib/log2zram/
	./overlay merge -l "${HDD_LOG}" -u "${ZDIR}/zram${DEV_NUM}/upper" >>${ZLOG} 2>&1 || return 1
	sh -x *.sh  >>${ZLOG} 2>&1 || return 1
	rm -v *.sh  >>${ZLOG} 2>&1 || return 1
	
}

case "$1" in
	start)
		echo "log2zram start $(date +%Y-%m-%d-%H:%M:%S)" >>${ZLOG}
		invoke-rc.d rsyslog stop >>${ZLOG} 2>&1 || exit 1
		mkdir -p $HDD_LOG  >>${ZLOG} 2>&1 || exit 1
		mount --verbose --bind $ZRAM_LOG/ $HDD_LOG/ >>${ZLOG} 2>&1 || exit 1
		mount --verbose --make-private $HDD_LOG/ >>${ZLOG} 2>&1 || exit 1
		createZramLogDrive >>${ZLOG} 2>&1 || exit 1
		mkdir -vp ${ZDIR}/zram${DEV_NUM} >>${ZLOG} 2>&1 || exit 1
		mount --verbose --types ext4 $MNT_OPTS /dev/zram${DEV_NUM} ${ZDIR}/zram${DEV_NUM}/ >>${ZLOG} 2>&1 || exit 1
		mkdir -vp ${ZDIR}/zram${DEV_NUM}/upper ${ZDIR}/zram${DEV_NUM}/workdir ${ZRAM_LOG} >>${ZLOG} 2>&1 || exit 1
		mount --verbose --types overlay -o redirect_dir=off,lowerdir=${HDD_LOG},upperdir=${ZDIR}/zram${DEV_NUM}/upper,workdir=${ZDIR}/zram${DEV_NUM}/workdir overlay${DEV_NUM} ${ZRAM_LOG} >>${ZLOG} 2>&1 || exit 1
		echo "/zram${DEV_NUM}" > ${ZSHARE}/zram-device-list
		invoke-rc.d rsyslog restart >>${ZLOG} 2>&1 || exit 1
		journalctl --flush >>${ZLOG} 2>&1 || exit 1
		;;

	stop)
		echo "log2zram stop $(date +%Y-%m-%d-%H:%M:%S)" >>${ZLOG}
		ZRAM_DEV=$(cat ${ZSHARE}/zram-device-list)
		DEV_NUM=$(echo "$ZRAM_DEV" | tr -dc '0-9')
		invoke-rc.d rsyslog stop >>${ZLOG} 2>&1
		if umount --verbose ${ZRAM_LOG}/ >>${ZLOG} 2>&1
		then
			echo "umount ${ZRAM_LOG}/" >>${ZLOG}
		else
		sleep .1
			invoke-rc.d rsyslog stop  >>${ZLOG} 2>&1
			umount --verbose -l ${ZRAM_LOG}/ >>${ZLOG} 2>&1 
		fi
		mergeOverlay >>${ZLOG} 2>&1
		if umount --verbose ${ZDIR}${ZRAM_DEV}/ >>${ZLOG} 2>&1
		then
			echo "umount ${ZDIR}{ZRAM_DEV}/" >>${ZLOG}
		else
			umount --verbose -l ${ZDIR}{ZRAM_DEV}/ >>${ZLOG} 2>&1 
		fi
		if umount --verbose $HDD_LOG/ >>${ZLOG} 2>&1
		then
			echo "umount $HDD_LOG/" >>${ZLOG}
		else
			sleep .1
			invoke-rc.d rsyslog stop  >>${ZLOG} 2>&1
			umount --verbose -l $HDD_LOG/ >>${ZLOG} 2>&1
		fi
		if [ "$DEV_NUM" = "0" ]
		then
			rmmod zram
		else
			echo "$DEV_NUM" > /sys/class/zram-control/hot_remove
		fi
		invoke-rc.d rsyslog restart >>${ZLOG} 2>&1
		;;

	*)
		echo "Usage: log2ram {start|stop}" >&2
		exit 1
		
esac
